apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myflask
  name: myflask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myflask
  template:
    metadata:
      labels:
        app: myflask
    spec:
      containers:
      - image: phjus/myflask-centos
        name: myflask
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myflask
  name: myflask
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: myflask
  type: NodePort

